fix(xlat): check definition of PLAT_XLAT_TABLES_DYNAMIC flag
When enabling -Wundef, we can see this warning:
include/lib/xlat_tables/xlat_tables_v2_helpers.h:81:5: error:
 'PLAT_XLAT_TABLES_DYNAMIC' is not defined, evaluates to '0'
 [-Werror=undef]
   81 | #if PLAT_XLAT_TABLES_DYNAMIC
      |     ^~~~~~~~~~~~~~~~~~~~~~~~

As the flag can be defined either with `call add_defines`, or directly
added to BL*_CFLAGS, the easier way to correct those warning is to
first check the flag is defined and then that it is set, with:
`#if defined(PLAT_XLAT_TABLES_DYNAMIC) && PLAT_XLAT_TABLES_DYNAMIC`

Change-Id: Ifbd20161d90e3eab46352393760fb0c01d24785c
Signed-off-by: Yann Gautier <yann.gautier@st.com>