fix(scmi): remove scmi_msg_get_voltage_handler
The function is not handled in scmi_process_message(), and there is no
ID for this protocol. Remove it.
This was seen when compiling with -Werror=missing-prototypes, there was
an error:
drivers/scmi-msg/entry.c:35:20: error: no previous prototype for
 'scmi_msg_get_voltage_handler' [-Werror=missing-prototypes]
   35 | scmi_msg_handler_t scmi_msg_get_voltage_handler(struct scmi_msg
                                                        *msg __unused)
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

Change-Id: I4091c8a76a9a19968ffde230567c1ac5f1ad409e
Signed-off-by: Yann Gautier <yann.gautier@st.com>