fix(io): correct SIZE_MAX management
Checking if the size or offset is above SIZE_MAX in the different io
files makes sense only for aarch32 platforms where SIZE_MAX is an u32.
On aarch64 system, this cannot happen as SIZE_MAX is the max of an u64.
And it triggers a warning, for example with clang:
drivers/io/io_block.c:199:16: error: result of comparison 'unsigned long
 long' > 18446744073709551615 is always false
 [-Werror,-Wtautological-type-limit-compare]
199 |         if (cur->size > (unsigned long long)SIZE_MAX) {
    |             ~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

However, the check on offset + size should be changed to an overflow
check with check_u64_overflow() for aarch64 platforms. That was already
the goal of `(offset + size < offset)` so replace it.

Change-Id: I76391ac86ddb2ab359b5401e6c776c3995c55ce3
Signed-off-by: Yann Gautier <yann.gautier@st.com>